### ISSUE TITLE
Installing without having root access

### ISSUE THREAD

**Issue by alexwailan** [sanger-pathogens/remove_blocks_from_aln#14]
Heyo!

So I am using a HPC where I don't have root access. Is there a way I can edit the install files to specify a directory to install the program to instead?

Many thanks,

Alex

**Comment by puethe** [comment]
Hi Alex,
how about using a virtual environment? Should work as this is a pure Python package. See e.g. [here](https://virtualenv.pypa.io/en/latest/). Once your virtual environment is activated, pip should install locally. The prerequisite is of course that a moderately recent version of Python is installed on your HPC cluster.
Cheers,
Christoph

**Comment by alexwailan** [comment]
This was a good suggestion. Eventually got this to work! Thanks for your quick reply! What a legend!
